name: queuetime
description: Smarter Touristenplaner mit Wartezeiten
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # Andere Pakete
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.6.1
  geolocator: ^10.1.0
  provider: ^6.1.2
  flutter_map: ^4.2.0
  latlong2: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
